-- Create users 
CREATE USER C##KGAG IDENTIFIED BY "pass" CONTAINER=ALL;
CREATE USER C##AANT IDENTIFIED BY "pass" CONTAINER=ALL;
CREATE USER C##CJOR IDENTIFIED BY "pass" CONTAINER=ALL;
CREATE USER C##EITU IDENTIFIED BY "pass" CONTAINER=ALL;
CREATE USER C##CDEM IDENTIFIED BY "pass" CONTAINER=ALL;

-- Allow them to log in
GRANT CREATE SESSION TO C##KGAG CONTAINER=ALL;
GRANT CREATE SESSION TO C##AANT CONTAINER=ALL;
GRANT CREATE SESSION TO C##CJOR CONTAINER=ALL;
GRANT CREATE SESSION TO C##EITU CONTAINER=ALL;
GRANT CREATE SESSION TO C##CDEM CONTAINER=ALL;

-- Grant DBA roles
GRANT DBA TO C##KGAG CONTAINER=ALL;
GRANT DBA TO C##AANT CONTAINER=ALL;
GRANT DBA TO C##CJOR CONTAINER=ALL;
GRANT DBA TO C##EITU CONTAINER=ALL;
GRANT DBA TO C##CDEM CONTAINER=ALL;

-- Grant SYSDBA / SYSOPER privileges
-- Only possible for common users
GRANT SYSDBA TO C##KGAG CONTAINER=ALL;
GRANT SYSDBA TO C##AANT CONTAINER=ALL;

GRANT SYSOPER TO C##CJOR CONTAINER=ALL;
GRANT SYSOPER TO C##EITU CONTAINER=ALL;
GRANT SYSOPER TO C##CDEM CONTAINER=ALL;

-- Additional roles
GRANT ADVISOR TO C##AANT CONTAINER=ALL;
GRANT ADVISOR TO C##EITU CONTAINER=ALL;

GRANT ALTER SESSION TO C##KGAG CONTAINER=ALL;
GRANT ALTER SESSION TO C##AANT CONTAINER=ALL;
GRANT ALTER SESSION TO C##CJOR CONTAINER=ALL;
GRANT ALTER SESSION TO C##EITU CONTAINER=ALL;
GRANT ALTER SESSION TO C##CDEM CONTAINER=ALL;
