-- Ensure password file is enabled (should already be EXCLUSIVE)
SHOW PARAMETER REMOTE_LOGIN_PASSWORDFILE;

-- Create users 
CREATE USER C##KGAG IDENTIFIED BY "pass" CONTAINER=ALL;
CREATE USER C##AANT IDENTIFIED BY "pass" CONTAINER=ALL;
CREATE USER C##CJOR IDENTIFIED BY "pass" CONTAINER=ALL;
CREATE USER C##EITU IDENTIFIED BY "pass" CONTAINER=ALL;
CREATE USER C##CDEM IDENTIFIED BY "pass" CONTAINER=ALL;

-- Allow them to log in
GRANT CREATE SESSION TO C##KGAG CONTAINER=ALL;
GRANT CREATE SESSION TO C##AANT CONTAINER=ALL;
GRANT CREATE SESSION TO C##CJOR CONTAINER=ALL;
GRANT CREATE SESSION TO C##EITU CONTAINER=ALL;
GRANT CREATE SESSION TO C##CDEM CONTAINER=ALL;

-- Grant DBA roles
GRANT DBA TO C##KGAG CONTAINER=ALL;
GRANT DBA TO C##AANT CONTAINER=ALL;
GRANT DBA TO C##CJOR CONTAINER=ALL;
GRANT DBA TO C##EITU CONTAINER=ALL;
GRANT DBA TO C##CDEM CONTAINER=ALL;

-- Grant SYSDBA / SYSOPER privileges
-- Only possible for common users
GRANT SYSDBA TO C##KGAG CONTAINER=ALL;
GRANT SYSDBA TO C##AANT CONTAINER=ALL;

GRANT SYSOPER TO C##CJOR CONTAINER=ALL;
GRANT SYSOPER TO C##EITU CONTAINER=ALL;
GRANT SYSOPER TO C##CDEM CONTAINER=ALL;

-- Additional roles
GRANT ADVISOR TO C##AANT CONTAINER=ALL;
GRANT ADVISOR TO C##EITU CONTAINER=ALL;

GRANT ALTER SESSION TO C##KGAG CONTAINER=ALL;
GRANT ALTER SESSION TO C##AANT CONTAINER=ALL;
GRANT ALTER SESSION TO C##CJOR CONTAINER=ALL;
GRANT ALTER SESSION TO C##EITU CONTAINER=ALL;
GRANT ALTER SESSION TO C##CDEM CONTAINER=ALL;


-- Switch into PDB
ALTER SESSION SET CONTAINER = ORCLPDB;

-- Create Users
CREATE USER APP_READONLY IDENTIFIED BY "pass";
CREATE USER ML_ANALYST IDENTIFIED BY "pass";
CREATE USER ML_DEVELOPER IDENTIFIED BY "pass";
CREATE USER STOCK_USER IDENTIFIED BY "pass";

-- Allow sessions
GRANT CREATE SESSION TO APP_READONLY;
GRANT CREATE SESSION TO ML_ANALYST;
GRANT CREATE SESSION TO ML_DEVELOPER;
GRANT CREATE SESSION TO STOCK_USER;

-- APP_READONLY ROLE: Dashboards / Power BI / APIs
-- Read-only access: only SELECT allowed
GRANT SELECT ANY TABLE TO APP_READONLY;

-- No quotas since user should not write to any tablespace
ALTER USER APP_READONLY QUOTA 0 ON USERS;

-- prevent object creation entirely
GRANT READ ANY TABLE TO APP_READONLY;

-- Give stock user unlimited quota on stocks data tablespace
ALTER USER STOCK_USER QUOTA UNLIMITED ON STOCKS_DATA;

-- ML_ANALYST ROLE: Querying, aggregation, materialized views
GRANT SELECT ANY TABLE TO ML_ANALYST;
GRANT CREATE MATERIALIZED VIEW TO ML_ANALYST;
GRANT CREATE SYNONYM TO ML_ANALYST;

-- No table creation required, so set quota to 0
ALTER USER ML_ANALYST QUOTA 0 ON USERS;

-- ML_DEVELOPER ROLE: Exploratory modeling & experimentation
GRANT SELECT ANY TABLE TO ML_DEVELOPER;

-- Allow experimentation (local scratch tables)
GRANT CREATE TABLE TO ML_DEVELOPER;
GRANT CREATE VIEW TO ML_DEVELOPER;

-- Allow them to save experimental objects in USERS tablespace
ALTER USER ML_DEVELOPER QUOTA UNLIMITED ON USERS;

