CREATE TABLE stock_user.stocks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR2(10) NOT NULL,
    trade_date TIMESTAMP NOT NULL,
    open NUMBER(10,4),
    low NUMBER(10,4),
    high NUMBER(10,4),
    close NUMBER(10,4),
    volume NUMBER(19),
    CONSTRAINT stocks_symbol_date_uniq UNIQUE (symbol, trade_date)
)
TABLESPACE stocks_data;

CREATE INDEX stock_user.STOCKS_SYMBOL_IDX ON stock_user.stocks (symbol) TABLESPACE stocks_index;

CREATE INDEX stock_user.STOCKS_DATE_IDX ON stock_user.stocks (trade_date) TABLESPACE stocks_index;
